/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'auth-login': RouteRecordInfo<'auth-login', '/auth/login', Record<never, never>, Record<never, never>>,
    'crm-clients': RouteRecordInfo<'crm-clients', '/crm/clients', Record<never, never>, Record<never, never>>,
    'crm-companies': RouteRecordInfo<'crm-companies', '/crm/companies', Record<never, never>, Record<never, never>>,
    'crm-companies-id': RouteRecordInfo<'crm-companies-id', '/crm/companies/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'crm-doctors': RouteRecordInfo<'crm-doctors', '/crm/doctors', Record<never, never>, Record<never, never>>,
    'crm-lottery': RouteRecordInfo<'crm-lottery', '/crm/lottery', Record<never, never>, Record<never, never>>,
    'cyclics-closing': RouteRecordInfo<'cyclics-closing', '/cyclics/closing', Record<never, never>, Record<never, never>>,
    'cyclics-cyclic': RouteRecordInfo<'cyclics-cyclic', '/cyclics/cyclic', Record<never, never>, Record<never, never>>,
    'cyclics-history': RouteRecordInfo<'cyclics-history', '/cyclics/history', Record<never, never>, Record<never, never>>,
    'cyclics-users': RouteRecordInfo<'cyclics-users', '/cyclics/users', Record<never, never>, Record<never, never>>,
    'finances-exchangerate': RouteRecordInfo<'finances-exchangerate', '/finances/exchangerate', Record<never, never>, Record<never, never>>,
    'finances-profitability': RouteRecordInfo<'finances-profitability', '/finances/profitability', Record<never, never>, Record<never, never>>,
    'fiscal-history': RouteRecordInfo<'fiscal-history', '/fiscal/history', Record<never, never>, Record<never, never>>,
    'inventory-expirations': RouteRecordInfo<'inventory-expirations', '/inventory/expirations', Record<never, never>, Record<never, never>>,
    'inventory-group-products': RouteRecordInfo<'inventory-group-products', '/inventory/groupProducts', Record<never, never>, Record<never, never>>,
    'inventory-products': RouteRecordInfo<'inventory-products', '/inventory/products', Record<never, never>, Record<never, never>>,
    'inventory-psychotropics': RouteRecordInfo<'inventory-psychotropics', '/inventory/psychotropics', Record<never, never>, Record<never, never>>,
    'inventory-stock': RouteRecordInfo<'inventory-stock', '/inventory/stock', Record<never, never>, Record<never, never>>,
    'inventory-traceability': RouteRecordInfo<'inventory-traceability', '/inventory/traceability', Record<never, never>, Record<never, never>>,
    'invoice-invoice-details': RouteRecordInfo<'invoice-invoice-details', '/invoice/invoiceDetails', Record<never, never>, Record<never, never>>,
    'invoice-invoice-form-edit': RouteRecordInfo<'invoice-invoice-form-edit', '/invoice/InvoiceFormEdit', Record<never, never>, Record<never, never>>,
    'invoice-invoice-for-order': RouteRecordInfo<'invoice-invoice-for-order', '/invoice/invoiceForOrder', Record<never, never>, Record<never, never>>,
    'invoice-invoice-loaded': RouteRecordInfo<'invoice-invoice-loaded', '/invoice/invoiceLoaded', Record<never, never>, Record<never, never>>,
    'invoice-invoice-ordered': RouteRecordInfo<'invoice-invoice-ordered', '/invoice/invoiceOrdered', Record<never, never>, Record<never, never>>,
    'invoice-invoices': RouteRecordInfo<'invoice-invoices', '/invoice/invoices', Record<never, never>, Record<never, never>>,
    'invoice-register': RouteRecordInfo<'invoice-register', '/invoice/register', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'lot-list': RouteRecordInfo<'lot-list', '/lot/list', Record<never, never>, Record<never, never>>,
    'lot-products': RouteRecordInfo<'lot-products', '/lot/products', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'suppliers-generar-pedido': RouteRecordInfo<'suppliers-generar-pedido', '/suppliers/generar-pedido', Record<never, never>, Record<never, never>>,
    'suppliers-list': RouteRecordInfo<'suppliers-list', '/suppliers/list', Record<never, never>, Record<never, never>>,
    'suppliers-supplieriaorderassistant': RouteRecordInfo<'suppliers-supplieriaorderassistant', '/suppliers/supplieriaorderassistant', Record<never, never>, Record<never, never>>,
    'tpv-credit': RouteRecordInfo<'tpv-credit', '/tpv/credit', Record<never, never>, Record<never, never>>,
    'tpv-order-general': RouteRecordInfo<'tpv-order-general', '/tpv/orderGeneral', Record<never, never>, Record<never, never>>,
    'tpv-order-user': RouteRecordInfo<'tpv-order-user', '/tpv/orderUser', Record<never, never>, Record<never, never>>,
    'tpv-quotation': RouteRecordInfo<'tpv-quotation', '/tpv/quotation', Record<never, never>, Record<never, never>>,
  }
}
