export const importTabs = [
  { title: 'Clientes', value: 'clientes', icon: 'tabler-users', filePattern: 'clientes.csv' },
  { title: 'Proveedores', value: 'proveedores', icon: 'tabler-truck', filePattern: 'proveedores.csv' },
  { title: 'Productos', value: 'productos', icon: 'tabler-package', filePattern: 'productos.csv' },
  { title: 'Inventario / Lotes', value: 'inventariolot', icon: 'tabler-clipboard-list', filePattern: 'inventariolot.csv' },
  { title: 'Gastos', value: 'gastos', icon: 'tabler-receipt-2', filePattern: 'gastos.csv' },
  { title: 'Cierres Diarios', value: 'cierres', icon: 'tabler-report-money', filePattern: 'cierres.csv' },
  { title: 'Catálogo y Ventas Externas (Excel)', value: 'external_catalog', icon: 'tabler-file-spreadsheet', filePattern: 'inventario.xlsx' },
]

export const fileSchemas = {
  clientes: [
    { field: 'identification', required: true, desc: 'Identificación del cliente (cédula o RIF)' },
    { field: 'identification_type', required: true, desc: 'Tipo de ID: V-, J-, G- o E-' },
    { field: 'name', required: true, desc: 'Nombres / Razón social' },
    { field: 'last_name', required: false, desc: 'Apellidos (opcional)' },
    { field: 'email', required: false, desc: 'Correo electrónico' },
    { field: 'phone', required: false, desc: 'Teléfono' },
    { field: 'address', required: false, desc: 'Dirección' },
    { field: 'birthdate', required: false, desc: 'Fecha de nacimiento (YYYY-MM-DD)' },
  ],
  proveedores: [
    { field: 'supplier_name', required: true, desc: 'Nombre comercial del proveedor' },
    { field: 'social_reason', required: false, desc: 'Razón social' },
    { field: 'sales_phone', required: false, desc: 'Teléfono de contacto de ventas' },
    { field: 'collections_phone', required: false, desc: 'Teléfono de cobranzas' },
    { field: 'credit_days', required: false, desc: 'Días de crédito otorgados (numérico)' },
    { field: 'payment_method', required: true, desc: 'Moneda habitual de pago (Bs / Divisas)' },
    { field: 'cash_payment', required: true, desc: '¿Acepta efectivo?: 1 (Sí) / 0 (No)' },
    { field: 'charges_igtf', required: true, desc: '¿Cobra IGTF?: 1 (Sí) / 0 (No)' },
  ],
  productos: [
    { field: 'barcode', required: true, desc: 'Código de barra del producto' },
    { field: 'name', required: true, desc: 'Nombre o descripción comercial' },
    { field: 'active_ingredient', required: false, desc: 'Principio activo' },
    { field: 'category_name', required: true, desc: 'Nombre de la Categoría' },
    { field: 'laboratory_name', required: false, desc: 'Nombre del Laboratorio' },
    { field: 'origin_name', required: false, desc: 'Nombre del Origen (Nacional / Importado)' },
    { field: 'cost_price', required: true, desc: 'Precio de costo (Ej: 1.20)' },
    { field: 'sale_price', required: true, desc: 'Precio de venta al público (Ej: 2.50)' },
    { field: 'iva', required: true, desc: '¿Aplica IVA?: 1 (Sí) / 0 (No)' },
    { field: 'psychotropic', required: true, desc: '¿Es psicotrópico?: 1 (Sí) / 0 (No)' },
    { field: 'from_colombia', required: true, desc: '¿Es traído de Colombia?: 1 (Sí) / 0 (No)' },
  ],
  inventariolot: [
    { field: 'barcode', required: true, desc: 'Código de barra de producto para enlazar catálogo' },
    { field: 'lot_number', required: false, desc: 'Número del lote físico' },
    { field: 'expiration_date', required: true, desc: 'Fecha de vencimiento (YYYY-MM-DD)' },
    { field: 'quantity', required: true, desc: 'Cantidad física en stock' },
    { field: 'cost_price', required: true, desc: 'Precio de costo del lote' },
    { field: 'location', required: false, desc: 'Ubicación física en tienda (Ej: Estante A-2)' },
    { field: 'supplier_name', required: false, desc: 'Nombre comercial del proveedor de origen' },
  ],
  gastos: [
    { field: 'name', required: true, desc: 'Descripción del gasto realizado' },
    { field: 'category_name', required: true, desc: 'Categoría del gasto' },
    { field: 'amount', required: true, desc: 'Monto total en Bolívares (Bs)' },
    { field: 'amount_usd', required: true, desc: 'Monto total en Dólares (USD)' },
    { field: 'currency', required: true, desc: 'Moneda del pago (Bs / USD)' },
    { field: 'expense_date', required: true, desc: 'Fecha del egreso (YYYY-MM-DD)' },
    { field: 'has_invoice', required: true, desc: '¿Posee factura formal?: 1 (Sí) / 0 (No)' },
    { field: 'is_deductible', required: true, desc: '¿Es gasto deducible?: 1 (Sí) / 0 (No)' },
  ],
  cierres: [
    { field: 'date', required: true, desc: 'Fecha del día del cuadre de caja (YYYY-MM-DD)' },
    { field: 'total_usd', required: true, desc: 'Total ventas Dólares (USD)' },
    { field: 'total_cop', required: true, desc: 'Total ventas Pesos (COP)' },
    { field: 'total_bs', required: true, desc: 'Total ventas Bolívares (Bs)' },
    { field: 'bs_card', required: true, desc: 'Monto cobrado con Tarjeta de Débito (Bs)' },
    { field: 'bs_mobile', required: true, desc: 'Monto cobrado con Pago Móvil (Bs)' },
    { field: 'usd_delivered', required: true, desc: 'Monto físico USD entregado a administración' },
    { field: 'cop_delivered', required: true, desc: 'Monto físico COP entregado a administración' },
    { field: 'bs_delivered', required: true, desc: 'Monto físico Bs entregado a administración' },
  ],
  external_catalog: [
    { field: 'PRD_CODIGO', required: false, desc: 'Código interno en el sistema externo' },
    { field: 'PRD_REFERENCIA', required: true, desc: 'Código de barra del producto (Homologación con Master)' },
    { field: 'PRD_DESCRIPCION', required: true, desc: 'Descripción / Nombre del producto' },
    { field: 'EIN_EXISTENCIA', required: true, desc: 'Stock físico actual en tienda' },
    { field: 'TPC_COSTOACTUAL', required: true, desc: 'Costo unitario actual en USD' },
    { field: 'DIM_EXENTO', required: true, desc: 'Indicador de IVA (G = Gravable 16%, E = Exento 0%)' },
    { field: 'EIN_EXISTENCIADIFERIDA', required: true, desc: 'Ventas totales acumuladas del año (para cálculo del sugerido)' },
  ],
}
