<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class GeneralSetting extends Model
{
   protected $table = 'general_settings';
    protected $fillable = [
        'fiscal_mode',
        'special_taxpayer_status',
        'all_foreign_sales_spe',
        'rif',
        'address',
        'income_statement_reset_date',
        'app_name',
        'app_rif',
        'app_logo',
        'app_favicon',
        'primary_color',
        'secondary_color',
        'tertiary_color',
        'footer_text',
        'blind_cash_closure',
        'business_type',
        'default_currency',
        'ecommerce_menu',
        'hero_title',
        'hero_subtitle',
        'hero_tagline',
        'hero_image',
        'hero_button_text',
        'section2_title',
        'section2_subtitle',
        'section2_tagline',
        'section2_image',
        'section2_button_text',
        'section3_title',
        'section3_subtitle',
        'section3_tagline',
        'section3_image',
        'section3_button_text',
        'cyclic_inventory_mode',
        'cyclic_inventory_barcode_required',
        'enable_lots',
        'tpv_mode',
        'enable_product_types',
        'enabled_product_types',
        'enable_favorites',
        'enable_variations',
        'enable_merge',
        'enable_groups',
        'product_form_fields',
        'enable_stock_control',
        'enable_expirations',
        'enable_brand_groups',
        'enable_donations',
        'enable_locations',
        'enable_optimization',
        'traceability_mode',
        'enable_dishes',
    ];

    protected $casts = [
        'all_foreign_sales_spe' => 'boolean',
        'blind_cash_closure' => 'boolean',
        'ecommerce_menu' => 'array',
        'cyclic_inventory_barcode_required' => 'boolean',
        'enable_lots' => 'boolean',
        'tpv_mode' => 'string',
        'enable_product_types' => 'boolean',
        'enabled_product_types' => 'array',
        'enable_favorites' => 'boolean',
        'enable_variations' => 'boolean',
        'enable_merge' => 'boolean',
        'enable_groups' => 'boolean',
        'product_form_fields' => 'array',
        'enable_stock_control' => 'boolean',
        'enable_expirations' => 'boolean',
        'enable_brand_groups' => 'boolean',
        'enable_donations' => 'boolean',
        'enable_locations' => 'boolean',
        'enable_optimization' => 'boolean',
        'enable_dishes' => 'boolean',
    ];
}
