-- phpMyAdmin SQL Dump
-- version 5.2.3
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost:3306
-- Tiempo de generación: 05-10-2026 a las 15:37:07
-- Versión del servidor: 8.0.46
-- Versión de PHP: 8.4.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `farmaciabs_erp2`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `supplier_connections`
--

CREATE TABLE `supplier_connections` (
  `id` bigint UNSIGNED NOT NULL,
  `supplier_id` bigint UNSIGNED NOT NULL,
  `type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ftp',
  `host` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `port` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `username` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `password` text COLLATE utf8mb4_unicode_ci,
  `path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pasv` tinyint(1) NOT NULL,
  `has_header` tinyint(1) NOT NULL,
  `invoice_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `invoice_structure` json DEFAULT NULL,
  `structure` json DEFAULT NULL,
  `secondary_structure` json DEFAULT NULL,
  `tertiary_structure` json DEFAULT NULL,
  `parse_using` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `last_connection` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla `supplier_connections`
--

INSERT INTO `supplier_connections` (`id`, `supplier_id`, `type`, `host`, `port`, `username`, `password`, `path`, `pasv`, `has_header`, `invoice_path`, `invoice_structure`, `structure`, `secondary_structure`, `tertiary_structure`, `parse_using`, `created_at`, `updated_at`, `last_connection`) VALUES
(1, 1005, 'ftp', 'ftp.dromega.com.ve', '21', 'clientemerida@dromega.com.ve', 'eyJpdiI6ImJONjVIL2t0YWVDK0RGQ3k1QnNMTHc9PSIsInZhbHVlIjoiUnUzdjIySFlBeGlmUVIyZ05WSDF0UT09IiwibWFjIjoiMjdkNDNmNDM0MTQwYTEzZWRhNjJiZmZjYmM2ODdjZTZjMGJhZDU1OThmZGZhNDRkYTE0MWY1NDA4ZmVkNGJiYiIsInRhZyI6IiJ9', 'Existencia/inventariomerida.txt', 0, 1, 'Facturas/7586', '{\"lines\": {\"0\": {\"type\": \"string\", \"field\": \"tipo\"}, \"1\": {\"type\": \"integer\", \"field\": \"fact_num\"}, \"2\": {\"type\": \"string\", \"field\": \"numcon\"}, \"3\": {\"type\": \"string\", \"field\": \"codigo_producto\"}, \"4\": {\"type\": \"string\", \"field\": \"barcode\"}, \"5\": {\"type\": \"string\", \"field\": \"descripcion_producto\"}, \"6\": {\"type\": \"integer\", \"field\": \"quantity\"}, \"8\": {\"type\": \"decimal\", \"field\": \"total_amount\"}, \"10\": {\"type\": \"decimal\", \"field\": \"unit_cost\"}, \"11\": {\"type\": \"string\", \"field\": \"lot_number\"}, \"12\": {\"type\": \"date\", \"field\": \"expiration_date\", \"format\": \"d/m/Y\"}, \"13\": {\"type\": \"decimal\", \"field\": \"porcentaje_iva\"}}, \"header\": {\"0\": {\"type\": \"string\", \"field\": \"tipo\"}, \"1\": {\"type\": \"integer\", \"field\": \"invoice_number\"}, \"2\": {\"type\": \"string\", \"field\": \"control_number\"}, \"3\": {\"type\": \"date\", \"field\": \"created_invoice_date\", \"format\": \"d/m/Y\"}, \"8\": {\"type\": \"decimal\", \"field\": \"total_amount\"}, \"13\": {\"type\": \"decimal\", \"field\": \"tax_amount\"}}, \"decimals\": 2, \"separator\": \";\", \"decimal_separator\": \".\"}', '[{\"type\": \"string\", \"target\": \"cod_supplier\", \"file_field\": \"codigo_producto\"}, {\"type\": \"string\", \"target\": \"barcode_match\", \"file_field\": \"codigo_barras\"}, {\"type\": \"string\", \"target\": \"name\", \"file_field\": \"descripcion_producto\"}, {\"type\": \"date\", \"target\": \"expiration\", \"file_field\": \"fecha_lote\"}, {\"type\": \"decimal\", \"file_field\": \"precio_unitario\"}, {\"type\": \"decimal\", \"file_field\": \"porcentaje_oferta_vigente\"}, {\"type\": \"decimal\", \"target\": \"unit_cost\", \"file_field\": \"precio_unitario_final\"}, {\"type\": \"integer\", \"target\": \"quantity\", \"file_field\": \"stock_disponible\"}]', NULL, NULL, 'null', NULL, '2026-09-11 13:41:51', '2026-10-05'),
(2, 1009, 'ftp', 'ftp1.vitalclinicdrogueria.com', '21', 'ftp1@vitalcliniconline.com', 'eyJpdiI6IlNwUlVvRFVheklNZW10dnI1blEweHc9PSIsInZhbHVlIjoic0FCNWE5TnJYelFXU3BuTWtiT2xNdz09IiwibWFjIjoiYTViNGMyN2ZiNmQ1NGZjMDRhNjVmNjNkMDFmNTI1YzBhN2ZlZDM1NTQ4NTY5MDRiNWY4YWYyZDE3ZjM4ZWZkZiIsInRhZyI6IiJ9', 'Articulos.txt', 1, 1, 'Facturas/3613', '{\"lines\": {\"0\": {\"type\": \"string\", \"field\": \"tipo\"}, \"1\": {\"type\": \"integer\", \"field\": \"fact_num\"}, \"2\": {\"type\": \"string\", \"field\": \"numcon\"}, \"3\": {\"type\": \"string\", \"field\": \"codigo_producto\"}, \"4\": {\"type\": \"string\", \"field\": \"barcode\"}, \"5\": {\"type\": \"string\", \"field\": \"descripcion_producto\"}, \"6\": {\"type\": \"integer\", \"field\": \"quantity\"}, \"10\": {\"type\": \"decimal\", \"field\": \"unit_cost\"}, \"11\": {\"type\": \"string\", \"field\": \"lot_number\"}, \"12\": {\"type\": \"date\", \"field\": \"expiration_date\", \"format\": \"d/m/Y\"}, \"13\": {\"type\": \"decimal\", \"field\": \"porcentaje_iva\"}, \"14\": {\"type\": \"boolean\", \"field\": \"tax_enabled\"}}, \"header\": {\"0\": {\"type\": \"string\", \"field\": \"tipo\"}, \"1\": {\"type\": \"integer\", \"field\": \"invoice_number\"}, \"2\": {\"type\": \"string\", \"field\": \"control_number\"}, \"3\": {\"type\": \"date\", \"field\": \"created_invoice_date\", \"format\": \"d/m/Y\"}, \"8\": {\"type\": \"decimal\", \"field\": \"total_usd\"}, \"13\": {\"type\": \"decimal\", \"field\": \"tax_amount\"}, \"14\": {\"type\": \"decimal\", \"field\": \"exchange_rate\"}}, \"decimals\": 2, \"separator\": \";\", \"decimal_separator\": \".\"}', '[{\"type\": \"string\", \"target\": \"cod_supplier\", \"file_field\": \"codigo_producto\"}, {\"type\": \"string\", \"target\": \"barcode_match\", \"file_field\": \"codigo_barras\"}, {\"type\": \"string\", \"target\": \"name\", \"file_field\": \"descripcion_producto\"}, {\"type\": \"date\", \"target\": \"expiration\", \"file_field\": \"fecha_lote\"}, {\"type\": \"decimal\", \"file_field\": \"precio_unitario\"}, {\"type\": \"decimal\", \"file_field\": \"porcentaje_oferta_vigente\"}, {\"type\": \"decimal\", \"target\": \"unit_cost_usd\", \"file_field\": \"precio_unitario_final\"}, {\"type\": \"integer\", \"target\": \"quantity\", \"file_field\": \"stock_disponible\"}]', NULL, NULL, 'null', NULL, '2026-09-09 22:43:07', '2026-09-04'),
(3, 1010, 'file', 'diana.drotaca@gmail.com', NULL, 'diana.drotaca@gmail.com', 'eyJpdiI6IkRoZnhwRXJuTWpuc0xjYTVWdVJJTXc9PSIsInZhbHVlIjoiTXJqeGFuWnNuZGhML2hOS3ducWUwQT09IiwibWFjIjoiZWY4ZGFjZWFmNDIzNDBkZmRlMTRlMzUzOTY1ZTY0NTZhYTQxMjhmYzM0NjVlNjViMjViMGUzYWRjOGI2YzY3NSIsInRhZyI6IiJ9', NULL, 0, 0, NULL, '{\"lines\": {\"0\": {\"type\": \"string\", \"field\": \"tipo\"}, \"1\": {\"type\": \"integer\", \"field\": \"fact_num\"}, \"2\": {\"type\": \"string\", \"field\": \"numcon\"}, \"3\": {\"type\": \"string\", \"field\": \"codigo_producto\"}, \"4\": {\"type\": \"string\", \"field\": \"barcode\"}, \"5\": {\"type\": \"string\", \"field\": \"descripcion_producto\"}, \"6\": {\"type\": \"integer\", \"field\": \"quantity\"}, \"10\": {\"type\": \"decimal\", \"field\": \"unit_cost\"}, \"11\": {\"type\": \"string\", \"field\": \"lot_number\"}, \"12\": {\"type\": \"date\", \"field\": \"expiration_date\", \"format\": \"d/m/Y\"}, \"13\": {\"type\": \"decimal\", \"field\": \"porcentaje_iva\"}}, \"filter\": {\"ends_with\": \".txt\", \"starts_with\": \"Factura\"}, \"header\": {\"0\": {\"type\": \"string\", \"field\": \"tipo\"}, \"1\": {\"type\": \"integer\", \"field\": \"invoice_number\"}, \"2\": {\"type\": \"string\", \"field\": \"control_number\"}, \"3\": {\"type\": \"date\", \"field\": \"exp_date\", \"format\": \"d/m/Y\"}, \"8\": {\"type\": \"decimal\", \"field\": \"total_amount\"}, \"13\": {\"type\": \"decimal\", \"field\": \"tax_amount\"}}, \"decimals\": 2, \"separator\": \";\", \"decimal_separator\": \".\"}', '{\"name\": \"g\", \"quantity\": \"n\", \"start_row\": \"9\", \"unit_cost\": \"o\", \"expiration\": \"l\", \"cod_supplier\": \"f\", \"file_keyword\": \"importados\", \"barcode_match\": \"k\", \"unit_cost_usd\": \"p\", \"active_ingredient\": null}', '{\"name\": \"h\", \"currency\": \"800\", \"quantity\": \"l\", \"start_row\": \"9\", \"unit_cost\": null, \"expiration\": \"j\", \"cod_supplier\": \"g\", \"file_keyword\": \"nacional\", \"barcode_match\": \"g\", \"unit_cost_usd\": \"n\", \"active_ingredient\": \"i\"}', NULL, 'null', NULL, '2026-09-10 15:42:59', '2026-10-05'),
(4, 1001, 'ftp', 'drocerca.proteoerp.org', '21', 'C008B3', 'eyJpdiI6IlFiOFZZQkM2MlRTWm9mR1FLcjdKZXc9PSIsInZhbHVlIjoidFlaMzRmSG5FOE5wejR3TjRxZ3M4UT09IiwibWFjIjoiYmEzMDY3OWQ1YTFiOTk3Y2M0ZDVkMzdiN2M2MzY3M2NkMjQ4MjcwNWEzNzUwNDJjYmFjODhiMzIyMzAzNzdkYSIsInRhZyI6IiJ9', 'inventario.txt', 1, 1, '/', '{\"mode\": \"flat\", \"lines\": {\"7\": {\"type\": \"string\", \"field\": \"codigo_producto\"}, \"8\": {\"type\": \"string\", \"field\": \"barcode\"}, \"9\": {\"type\": \"string\", \"field\": \"descripcion_producto\"}, \"10\": {\"type\": \"decimal\", \"field\": \"quantity\"}, \"12\": {\"type\": \"decimal\", \"field\": \"unit_cost\"}, \"13\": {\"type\": \"decimal\", \"field\": \"total_cost\"}, \"14\": {\"type\": \"decimal\", \"field\": \"porcentaje_iva\"}, \"16\": {\"type\": \"string\", \"field\": \"lot_number\"}, \"17\": {\"type\": \"date\", \"field\": \"expiration_date\"}}, \"filter\": {\"ends_with\": \".txt\", \"starts_with\": \"F\"}, \"header\": {\"0\": {\"type\": \"string\", \"field\": \"invoice_number\"}, \"1\": {\"type\": \"date\", \"field\": \"created_invoice_date\"}, \"2\": {\"type\": \"date\", \"field\": \"exp_date\"}, \"3\": {\"type\": \"decimal\", \"field\": \"exempt_amount\"}, \"5\": {\"type\": \"decimal\", \"field\": \"tax_amount\"}, \"6\": {\"type\": \"decimal\", \"field\": \"total_amount\"}, \"18\": {\"type\": \"decimal\", \"field\": \"exchange_rate\"}}, \"separator\": \";\"}', '[{\"type\": \"string\", \"target\": \"cod_supplier\", \"file_field\": \"Codigo\"}, {\"type\": \"string\", \"target\": \"barcode_match\", \"file_field\": \"CodBarras\"}, {\"type\": \"string\", \"target\": \"name\", \"file_field\": \"Descripcion\"}, {\"type\": \"decimal\", \"target\": \"exisMerida\", \"file_field\": \"exisMerida\"}, {\"type\": \"decimal\", \"target\": \"exisCaracas\", \"file_field\": \"exisCaracas\"}, {\"type\": \"decimal\", \"target\": \"exisOriente\", \"file_field\": \"exisOriente\"}, {\"type\": \"string\", \"file_field\": \"Marca\"}, {\"type\": \"decimal\", \"file_field\": \"Precio\"}, {\"type\": \"decimal\", \"target\": \"unit_cost\", \"file_field\": \"Oferta\"}, {\"type\": \"string\", \"file_field\": \"Grupo\"}, {\"type\": \"date\", \"target\": \"expiration\", \"file_field\": \"VenceMerida\"}, {\"type\": \"date\", \"file_field\": \"VenceCentro\"}, {\"type\": \"date\", \"file_field\": \"VenceOriente\"}, {\"type\": \"string\", \"target\": \"active_ingredient\", \"file_field\": \"Principio\"}, {\"type\": \"decimal\", \"file_field\": \"Escala\"}, {\"type\": \"decimal\", \"file_field\": \"DescXEscala\"}, {\"type\": \"decimal\", \"file_field\": \"Bonifica\"}, {\"type\": \"decimal\", \"file_field\": \"CantBonifica\"}, {\"type\": \"decimal\", \"file_field\": \"DifPorcentaje\"}]', NULL, NULL, 'null', NULL, '2026-09-09 18:39:14', '2026-10-05'),
(5, 1011, 'api', 'https://comparadores.drogueriascobeca.com/api/login', '21', 'F31373', 'eyJpdiI6Ii9pSnVYR0VDNzZ3RWxySk5UUzlBN3c9PSIsInZhbHVlIjoiOUZiMEZZMTJ2bEUrM3NaT3E2NXhpZz09IiwibWFjIjoiMGI1OTc3ZWUwYmY3NDVkMTY4YmQwODY3MThlMzQ1ZDE4MzU1YmE0NDE0YTRkYzM4MGYzYjBlMWM5MDBlZmQ5YiIsInRhZyI6IiJ9', 'https://comparadores.drogueriascobeca.com/api/articulos/drogueria', 0, 1, 'https://comparadores.drogueriascobeca.com/api/facturas/resumen', '{\"mode\": \"flat\", \"lines\": {\"26\": {\"type\": \"integer\", \"field\": \"fact_num\"}, \"27\": {\"type\": \"string\", \"field\": \"codigo_producto\"}, \"28\": {\"type\": \"string\", \"field\": \"descripcion_producto\"}, \"29\": {\"type\": \"string\", \"field\": \"lot_number\"}, \"30\": {\"type\": \"date\", \"field\": \"expiration_date\", \"format\": \"d/m/Y\"}, \"33\": {\"type\": \"integer\", \"field\": \"quantity\"}, \"37\": {\"type\": \"decimal\", \"field\": \"porcentaje_iva\"}, \"40\": {\"type\": \"decimal\", \"field\": \"unit_cost\"}, \"43\": {\"type\": \"decimal\", \"field\": \"total_cost\"}, \"48\": {\"type\": \"string\", \"field\": \"barcode\"}, \"49\": {\"type\": \"string\", \"field\": \"numcon\"}}, \"header\": {\"1\": {\"type\": \"integer\", \"field\": \"invoice_number\"}, \"4\": {\"type\": \"decimal\", \"field\": \"total_amount\"}, \"6\": {\"type\": \"date\", \"field\": \"exp_date\", \"format\": \"d/m/Y\"}, \"13\": {\"type\": \"string\", \"field\": \"control_number\"}, \"15\": {\"type\": \"decimal\", \"field\": \"exchange_rate\"}, \"16\": {\"type\": \"decimal\", \"field\": \"tax_amount\"}}, \"decimals\": 2, \"separator\": \";\", \"decimal_separator\": \".\"}', '{\"12\": {\"type\": \"string\", \"target\": \"cod_supplier\", \"file_field\": \"cod_articulo\"}, \"13\": {\"type\": \"string\", \"target\": \"barcode_match\", \"file_field\": \"cod_barra\"}, \"14\": {\"type\": \"string\", \"target\": \"name\", \"file_field\": \"desc_articulo\"}, \"17\": {\"type\": \"integer\", \"target\": \"quantity\", \"file_field\": \"existencia\"}, \"20\": {\"type\": \"decimal\", \"target\": \"unit_cost\", \"file_field\": \"monto_final\"}, \"28\": {\"type\": \"date\", \"target\": \"expiration\", \"file_field\": \"fecha_Expire_ned\"}, \"29\": {\"type\": \"string\", \"target\": \"active_ingredient\", \"file_field\": \"desc_componente_base\"}, \"30\": {\"type\": \"string\", \"target\": \"laboratory\", \"file_field\": \"desc_proveedor\"}}', NULL, NULL, 'null', NULL, '2026-09-11 13:42:52', '2026-10-05'),
(6, 1017, 'ftp', 'jkserverom.drogueriajoskar.com', '21', 'CLI_V241509806', 'eyJpdiI6Ik1ITEgvVUlsSkJPM2JqMHQrQmhsdUE9PSIsInZhbHVlIjoiRDllMFpBR2ticTFYc04wVGVFUW5mZz09IiwibWFjIjoiYmZmOWFmNWM1YjYxMzkzZjI4MDNiZDFjYjE1YzVlMjdlMDM1ZWE4MDdkYzAyYmI2OWRiZTMzNmNkZDg4ZWU5MiIsInRhZyI6IiJ9', 'inventario.txt', 1, 0, '', NULL, '[{\"type\": \"string\", \"target\": \"cod_supplier\", \"file_field\": \"codigo_interno\"}, {\"type\": \"string\", \"target\": \"barcode_match\", \"file_field\": \"codigo_barras\"}, {\"type\": \"string\", \"target\": \"name\", \"file_field\": \"descripcion_producto\"}, {\"type\": \"date\", \"target\": \"expiration\", \"file_field\": \"fecha_lote\"}, {\"type\": \"decimal\", \"file_field\": \"precio_unitario\"}, {\"type\": \"decimal\", \"file_field\": \"porcentaje_oferta_vigente\"}, {\"type\": \"decimal\", \"target\": \"unit_cost_usd\", \"file_field\": \"precio_final\"}, {\"type\": \"integer\", \"target\": \"quantity\", \"file_field\": \"stock\"}]', NULL, NULL, 'null', NULL, '2026-01-15 05:02:10', '2026-01-15'),
(7, 1014, 'dronena_bot', 'https://www.dronena.com/NuevaExperiencia/', NULL, 'D719', 'eyJpdiI6ImlCWHBLRjRuQlE3WndtbGV5TjJaY0E9PSIsInZhbHVlIjoiVTgyTUF6ZUJOckJVekQvb3pCa1o5Zz09IiwibWFjIjoiOWRhZmFjMzMxNzgzNWE1NTc3NTE3MzZjY2Y3NGFiYzIzNWM5ZGI1ZDMwNWRkNmFjY2ZjY2U2MGI2N2IwZTg3ZSIsInRhZyI6IiJ9', NULL, 1, 1, NULL, '{\"mode\": \"grouped\", \"lines\": [{\"type\": \"string\", \"field\": \"tipo\"}, {\"type\": \"string\", \"field\": \"invoice_number\"}, {\"type\": \"string\", \"field\": \"cod_supplier\"}, {\"type\": \"string\", \"field\": \"name\"}, {\"type\": \"integer\", \"field\": \"quantity\"}, {\"type\": \"decimal\", \"field\": \"unit_cost\", \"decimals\": 2}, {\"type\": \"decimal\", \"field\": \"total_cost\", \"decimals\": 2}, {\"type\": \"string\", \"field\": \"barcode\"}, {\"type\": \"date\", \"field\": \"expiration_date\", \"format\": \"d/m/Y\"}], \"filter\": {\"ends_with\": \".txt\", \"starts_with\": \"\"}, \"header\": [{\"type\": \"string\", \"field\": \"tipo\"}, {\"type\": \"string\", \"field\": \"invoice_number\"}, {\"type\": \"decimal\", \"field\": \"total_amount\", \"decimals\": 2}, {\"type\": \"datetime\", \"field\": \"created_invoice_date\", \"format\": \"d/m/Y g:i:s A\"}, {\"type\": \"decimal\", \"field\": \"exchange_rate\", \"decimals\": 2}, {\"type\": \"decimal\", \"field\": \"total_usd\"}], \"separator\": \"\\t\"}', '{\"0\": {\"type\": \"string\", \"target\": \"cod_supplier\", \"file_field\": \"A\"}, \"1\": {\"type\": \"string\", \"target\": \"name\", \"file_field\": \"B\"}, \"2\": {\"type\": \"decimal\", \"target\": \"unit_cost\", \"file_field\": \"C\"}, \"3\": {\"type\": \"decimal\", \"target\": \"quantity\", \"file_field\": \"D\"}, \"6\": {\"type\": \"decimal\", \"target\": \"discount_percentage\", \"file_field\": \"G\"}, \"9\": {\"type\": \"string\", \"target\": \"barcode_match\", \"file_field\": \"J\"}, \"13\": {\"type\": \"date\", \"target\": \"expiration\", \"file_field\": \"N\"}}', NULL, NULL, '[{\"name\": \"codigo\", \"width\": 7}, {\"name\": \"descripcion\", \"width\": 38}, {\"name\": \"precio\", \"width\": 15}, {\"name\": \"cantidad\", \"width\": 12}, {\"name\": \"dcto\", \"width\": 8}, {\"name\": \"margenfar\", \"width\": 8}, {\"name\": \"dcto_ufi\", \"width\": 15}, {\"name\": \"empaque\", \"width\": 9}, {\"name\": \"dcto_empaque\", \"width\": 11}, {\"name\": \"codbarras\", \"width\": 20}, {\"name\": \"tipo\", \"width\": 5}, {\"name\": \"codprov\", \"width\": 8}, {\"name\": \"lote\", \"width\": 30}, {\"name\": \"fecha_exp\", \"width\": 16}, {\"name\": \"regulado\", \"width\": 7}, {\"name\": \"cadena_frio\", \"width\": 14}, {\"name\": \"dcto_comer\", \"width\": 14}, {\"name\": \"dcto_pp\", \"width\": 10}, {\"name\": \"original\", \"width\": 10}, {\"name\": \"umf\", \"width\": 9}, {\"name\": \"fechaingreso\", \"width\": 14}, {\"name\": \"adm\", \"width\": 1}]', NULL, '2026-09-30 15:50:25', '2026-10-05'),
(8, 1007, 'file', 'DROVIDA (Excel)', NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, '{\"name\": \"a\", \"currency\": \"400\", \"quantity\": \"h\", \"start_row\": \"3\", \"unit_cost\": null, \"expiration\": \"f\", \"cod_supplier\": null, \"barcode_match\": \"null\", \"unit_cost_usd\": \"e\", \"active_ingredient\": null}', NULL, NULL, NULL, '2026-01-06 01:57:31', '2026-02-23 18:59:41', '2026-02-23'),
(9, 1013, 'file', 'droguerialaesencialtachira@gmail.com', NULL, 'droguerialaesencialtachira@gmail.com', NULL, NULL, 0, 0, NULL, NULL, '{\"name\": \"a\", \"currency\": \"400\", \"quantity\": \"null\", \"start_row\": \"11\", \"unit_cost\": null, \"expiration\": \"null\", \"cod_supplier\": null, \"barcode_match\": \"null\", \"unit_cost_usd\": \"e\", \"active_ingredient\": \"c\"}', NULL, NULL, NULL, '2026-01-06 02:02:33', '2026-09-09 20:21:24', '2026-10-05'),
(10, 1006, 'api', 'https://app.drosymca.com', NULL, 'farmab.sucre2024@gmail.com', 'eyJpdiI6IitWRFdsdmd3cjNZL0RZUmwxS0t2anc9PSIsInZhbHVlIjoiS1o0ZWhpbFdRRHdqbkh2OExxaHBFQT09IiwibWFjIjoiYWE0MGQ2MDlmOGU4NTMyNGVkMDU2YzQ2ZDU3ZDk4NTc5ODZlZjUzZmI2OGMzMmFlYzkwMDA0OWM4NjA2NWNiZiIsInRhZyI6IiJ9', 'https://app.drosymca.com/facturas', 0, 1, 'https://app.drosymca.com/cobranza', NULL, '{\"name\": \"c\", \"currency\": \"420\", \"quantity\": \"i\", \"start_row\": \"24\", \"unit_cost\": null, \"expiration\": \"h\", \"cod_supplier\": \"a\", \"barcode_match\": \"b\", \"unit_cost_usd\": \"f\", \"active_ingredient\": \"g\"}', NULL, NULL, NULL, '2026-01-06 02:08:59', '2026-09-04 14:23:40', '2026-10-05'),
(11, 1018, 'file', 'MEGAFAR (Excel)', NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, '{\"name\": \"E\", \"quantity\": \"G\", \"start_row\": \"4\", \"unit_cost\": \"380\", \"expiration\": \"H\", \"cod_supplier\": \"D\", \"barcode_match\": \"B\", \"unit_cost_usd\": \"I\", \"active_ingredient\": null}', NULL, NULL, NULL, '2026-01-06 04:05:23', '2026-03-12 02:06:45', '2026-09-03'),
(12, 1019, 'file', 'libiarene01@gmail.com', NULL, 'libiarene01@gmail.com', NULL, NULL, 0, 0, NULL, NULL, '{\"name\": \"d\", \"currency\": \"800\", \"quantity\": \"g\", \"start_row\": \"9\", \"unit_cost\": null, \"expiration\": \"f\", \"cod_supplier\": \"c\", \"barcode_match\": \"b\", \"unit_cost_usd\": \"g\", \"active_ingredient\": \"e\"}', NULL, NULL, NULL, '2026-01-06 04:13:12', '2026-09-09 20:55:14', '2026-09-16'),
(13, 1002, 'api', 'https://apienterprise.cristmedicals.com', NULL, 'FAR00818', 'eyJpdiI6ImdwNHlNRnlkT09KaGdJUUNqckVDTlE9PSIsInZhbHVlIjoiNS8yM2xKb0IxakxFUFBsQk1namNsVkp5eHZqREh4SEQ1VVVZV0k5KzZsTDFTeXZYSmxNUzNhMzNFS2JBcEdEeTVDOEpITHcrYUYrL2dLdGxmdHVieG1valhOQVk3VlRzMG4zdHpKZlZEaXl4aS9sUURrQTVNQWkzOHJydnAyN0IiLCJtYWMiOiI1YTM4MDE5NGZkZjQyOTEyY2M2ZmUwNzRiOWE4N2UzYzgyYzExMDY4ZWUyOTVmYzRlNTU4MzlkMWYxZWNjZDA2IiwidGFnIjoiIn0=', 'https://apienterprise.cristmedicals.com/api/v1/articulos', 0, 1, 'https://apienterprise.cristmedicals.com/api/v1/facturas', '{\"mode\": \"grouped\", \"lines\": [{\"type\": \"string\", \"field\": \"barcode\", \"original_field\": \"sku\"}, {\"type\": \"string\", \"field\": \"name\", \"original_field\": \"descrip\"}, {\"type\": \"integer\", \"field\": \"quantity\", \"original_field\": \"cant\"}, {\"type\": \"decimal\", \"field\": \"unit_cost\", \"original_field\": \"neto_und\"}, {\"type\": \"decimal\", \"field\": \"total_cost\", \"original_field\": \"total\"}], \"header\": [{\"type\": \"string\", \"field\": \"invoice_number\", \"original_field\": \"fact_num\"}, {\"type\": \"date\", \"field\": \"date\", \"format\": \"Y-m-d\", \"original_field\": \"fec_emis\"}, {\"type\": \"decimal\", \"field\": \"total_amount\", \"original_field\": \"sub_total\"}, {\"type\": \"decimal\", \"field\": \"tax_amount\", \"original_field\": \"iva16\"}, {\"type\": \"decimal\", \"field\": \"exempt_amount\", \"original_field\": \"exento\"}, {\"type\": \"decimal\", \"field\": \"exchange_rate\", \"original_field\": \"tasa\"}]}', '[{\"type\": \"string\", \"target\": \"name\", \"file_field\": \"des_art\"}, {\"type\": \"string\", \"target\": \"barcode_match\", \"file_field\": \"codigo_barra\"}, {\"type\": \"decimal\", \"target\": \"unit_cost_usd\", \"file_field\": \"precio_con_descuento\"}, {\"type\": \"string\", \"target\": \"cod_supplier\", \"file_field\": \"co_art\"}]', NULL, NULL, NULL, '2026-01-06 14:11:44', '2026-09-15 23:00:47', '2026-10-05'),
(14, 1003, 'file', 'drogueriajayeventas7@gmail.com', NULL, 'drogueriajayeventas7@gmail.com', NULL, NULL, 0, 0, NULL, NULL, '{\"name\": \"d\", \"currency\": \"785.06\", \"quantity\": \"i\", \"start_row\": \"12\", \"unit_cost\": null, \"expiration\": null, \"cod_supplier\": \"a\", \"file_keyword\": \"importado\", \"barcode_match\": \"b\", \"unit_cost_usd\": \"h\", \"active_ingredient\": null}', '{\"name\": \"d\", \"currency\": \"785.06\", \"quantity\": \"i\", \"start_row\": \"12\", \"unit_cost\": null, \"expiration\": null, \"cod_supplier\": \"a\", \"file_keyword\": \"importado\", \"barcode_match\": \"b\", \"unit_cost_usd\": \"h\", \"active_ingredient\": null}', NULL, NULL, '2026-01-06 14:38:36', '2026-09-09 21:03:55', '2026-10-05'),
(15, 1004, 'file', 'drogueriandinaca@gmail.com', NULL, 'drogueriandinaca@gmail.com', NULL, NULL, 0, 0, NULL, NULL, '{\"name\": \"a\", \"currency\": \"818\", \"quantity\": \"b\", \"start_row\": \"3\", \"unit_cost\": null, \"expiration\": null, \"cod_supplier\": \"b\", \"file_keyword\": null, \"barcode_match\": \"b\", \"unit_cost_usd\": \"b\", \"active_ingredient\": null}', '{\"name\": \"a\", \"currency\": \"818\", \"quantity\": \"b\", \"start_row\": \"3\", \"unit_cost\": null, \"expiration\": null, \"cod_supplier\": \"b\", \"file_keyword\": \"nacional\", \"barcode_match\": \"b\", \"unit_cost_usd\": \"b\", \"active_ingredient\": null}', '{\"name\": \"b\", \"currency\": \"818\", \"quantity\": \"h\", \"start_row\": \"4\", \"unit_cost\": null, \"expiration\": null, \"cod_supplier\": \"a\", \"file_keyword\": \"genial\", \"barcode_match\": \"a\", \"unit_cost_usd\": \"c\", \"active_ingredient\": null}', NULL, '2026-01-06 14:55:48', '2026-09-09 20:49:47', '2026-10-05'),
(16, 1008, 'file', 'SUMIANDES (Excel)', NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, '{\"name\": \"b\", \"currency\": \"430\", \"quantity\": \"null\", \"start_row\": \"1\", \"unit_cost\": null, \"expiration\": \"null\", \"cod_supplier\": \"13\", \"barcode_match\": \"null\", \"unit_cost_usd\": \"f\", \"active_ingredient\": \"c\"}', NULL, NULL, NULL, '2026-01-09 14:30:34', '2026-03-12 02:05:08', '2026-09-03'),
(17, 1016, 'file', 'vickmedicaltelemarketing5@gmail.com', NULL, 'vickmedicaltelemarketing5@gmail.com', NULL, NULL, 0, 0, NULL, NULL, '{\"name\": \"d\", \"quantity\": \"h\", \"start_row\": \"5\", \"unit_cost\": \"n\", \"expiration\": \"e\", \"cod_supplier\": \"c\", \"barcode_match\": \"b\", \"unit_cost_usd\": \"m\", \"active_ingredient\": null}', NULL, NULL, NULL, '2026-01-13 15:24:23', '2026-09-09 19:37:41', '2026-10-05'),
(18, 1015, 'file', 'DROGUERÍA RR FARMACOS OTC (Excel)', NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, '{\"name\": \"b\", \"quantity\": \"null\", \"start_row\": \"6\", \"unit_cost\": \"f\", \"expiration\": \"l\", \"cod_supplier\": \"a\", \"barcode_match\": \"i\", \"unit_cost_usd\": \"e\", \"active_ingredient\": \"j\"}', NULL, NULL, NULL, '2026-01-13 15:30:05', '2026-08-18 00:36:05', '2026-09-14'),
(19, 1032, 'ftp', '186.167.68.54', '58021', 'c3041', 'eyJpdiI6ImlvamcxL2dnRC9vK0xBc2xYVDJrbmc9PSIsInZhbHVlIjoiaUJHWWdYMkk1MFc1bFhERDBpU1huQT09IiwibWFjIjoiZjZhYTc5NDZiYTRkN2Q4NDA4YzBjMDQyN2I0MjdhZjUyZGJmNzFkNWFmOTUyZGE0YTUxM2JmNzJjMzMyNTQ1ZiIsInRhZyI6IiJ9', 'inventario.txt', 1, 0, '/Facturas', NULL, '[]', NULL, NULL, NULL, '2026-09-04 14:35:44', '2026-09-04 14:35:44', '2026-09-22'),
(20, 1034, 'file', 'DISTRIROSHI (Excel)', NULL, 'ventasdistriroshi1@gmail.com', NULL, NULL, 0, 0, NULL, NULL, '{\"name\": \"d\", \"currency\": \"820.10\", \"quantity\": \"b\", \"start_row\": \"5\", \"unit_cost\": null, \"expiration\": \"g\", \"cod_supplier\": \"a\", \"barcode_match\": \"b\", \"unit_cost_usd\": \"h\", \"active_ingredient\": \"e\"}', NULL, NULL, NULL, '2026-09-09 19:08:43', '2026-09-09 19:16:39', '2026-09-16'),
(21, 1035, 'file', 'drogueriaautanaad@gmail.com', NULL, 'drogueriaautanaad@gmail.com', NULL, NULL, 0, 0, NULL, NULL, '{\"name\": \"c\", \"currency\": \"818\", \"quantity\": \"e\", \"start_row\": \"31\", \"unit_cost\": null, \"expiration\": \"g\", \"cod_supplier\": \"b\", \"barcode_match\": \"b\", \"unit_cost_usd\": \"h\", \"active_ingredient\": \"d\"}', NULL, NULL, NULL, '2026-09-09 20:16:12', '2026-09-09 20:17:15', '2026-09-09'),
(22, 1036, 'file', 'nelson.imedicalfenix@gmail.com', NULL, 'nelson.imedicalfenix@gmail.com', NULL, NULL, 0, 0, NULL, NULL, '{\"name\": \"c\", \"currency\": \"800\", \"quantity\": \"f\", \"start_row\": \"9\", \"unit_cost\": null, \"expiration\": null, \"cod_supplier\": \"b\", \"barcode_match\": \"c\", \"unit_cost_usd\": \"f\", \"active_ingredient\": null}', NULL, NULL, NULL, '2026-09-09 20:26:08', '2026-09-09 20:27:04', '2026-10-05'),
(23, 1037, 'file', 'libiarene01@gmail.com', NULL, 'libiarene01@gmail.com', NULL, NULL, 1, 0, NULL, NULL, '[]', NULL, NULL, NULL, '2026-09-09 20:53:05', '2026-09-09 20:53:05', NULL),
(24, 1038, 'file', 'carmenasc75@gmail.com', NULL, 'carmenasc75@gmail.com', NULL, NULL, 1, 0, NULL, NULL, '{\"name\": \"b\", \"currency\": \"800\", \"quantity\": \"1\", \"start_row\": \"8\", \"unit_cost\": null, \"expiration\": \"g\", \"cod_supplier\": \"1\", \"file_keyword\": null, \"barcode_match\": \"1\", \"unit_cost_usd\": \"h\", \"active_ingredient\": \"e\"}', NULL, NULL, NULL, '2026-09-09 21:22:08', '2026-09-09 21:23:30', '2026-09-16'),
(25, 1039, 'file', 'delgadosuarezalfredoj@gmail.com', NULL, 'delgadosuarezalfredoj@gmail.com', NULL, NULL, 1, 0, NULL, NULL, '{\"name\": \"b\", \"currency\": \"800\", \"quantity\": \"1\", \"start_row\": \"4\", \"unit_cost\": null, \"expiration\": null, \"cod_supplier\": \"1\", \"file_keyword\": null, \"barcode_match\": \"1\", \"unit_cost_usd\": \"c\", \"active_ingredient\": null}', NULL, NULL, NULL, '2026-09-09 21:25:38', '2026-09-09 21:26:34', '2026-09-22'),
(26, 1011, 'ftp', 'step03.efficacis.com', '21', 'USRFTP31373', 'eyJpdiI6Ii80bXZGUmdKcXNsdjBrQXZFdTF4N1E9PSIsInZhbHVlIjoiUmRVRGtrRWlOTXVlZDZScmpJN3Qwdz09IiwibWFjIjoiYjQ2MDIxNmVjMmMwZGEzZTk5YWYwMDMwYzRjMDFmOGUzNjA4NDg2M2RkZTA5ZDRiOTEzNDRmMDc2ZmNkYTg1NiIsInRhZyI6IiJ9', NULL, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, '2026-09-10 23:51:47', '2026-09-10 23:51:47', '2026-10-05'),
(27, 1014, 'ftp', 'ftp.dronena.com', '21', 'D719-foraneo', 'eyJpdiI6IkllSGpGVWRlWUIvVVdBcDQvdVY5cWc9PSIsInZhbHVlIjoiczEwVFJZMHVVZUVrNjRqQjFxWTBodz09IiwibWFjIjoiMzUzZjlmOWY5ZmI0OWE5MTBlM2I5NDU2NmQ4MDhiYWMwZGU1M2I4NzFhNGY2MjQyMWZhMWNiOTVhMzgwZTcwNSIsInRhZyI6IiJ9', 'Clientes/d719/Inventario.txt', 0, 1, 'Clientes/d719/Factura', '{\"mode\": \"grouped\", \"lines\": [{\"type\": \"string\", \"field\": \"tipo\"}, {\"type\": \"string\", \"field\": \"invoice_number\"}, {\"type\": \"string\", \"field\": \"cod_supplier\"}, {\"type\": \"string\", \"field\": \"name\"}, {\"type\": \"integer\", \"field\": \"quantity\"}, {\"type\": \"decimal\", \"field\": \"unit_cost\", \"decimals\": 2}, {\"type\": \"decimal\", \"field\": \"total_cost\", \"decimals\": 2}, {\"type\": \"string\", \"field\": \"barcode\"}, {\"type\": \"date\", \"field\": \"expiration_date\", \"format\": \"d/m/Y\"}], \"filter\": {\"ends_with\": \".txt\", \"starts_with\": \"\"}, \"header\": [{\"type\": \"string\", \"field\": \"tipo\"}, {\"type\": \"string\", \"field\": \"invoice_number\"}, {\"type\": \"decimal\", \"field\": \"total_amount\", \"decimals\": 2}, {\"type\": \"datetime\", \"field\": \"created_invoice_date\", \"format\": \"d/m/Y g:i:s A\"}, {\"type\": \"decimal\", \"field\": \"exchange_rate\", \"decimals\": 2}, {\"type\": \"decimal\", \"field\": \"total_usd\"}], \"separator\": \"\\t\"}', '{\"0\": {\"type\": \"string\", \"target\": \"cod_supplier\", \"file_field\": \"A\"}, \"1\": {\"type\": \"string\", \"target\": \"name\", \"file_field\": \"B\"}, \"2\": {\"type\": \"decimal\", \"target\": \"unit_cost\", \"file_field\": \"C\"}, \"3\": {\"type\": \"decimal\", \"target\": \"quantity\", \"file_field\": \"D\"}, \"6\": {\"type\": \"decimal\", \"target\": \"discount_percentage\", \"file_field\": \"G\"}, \"9\": {\"type\": \"string\", \"target\": \"barcode_match\", \"file_field\": \"J\"}, \"13\": {\"type\": \"date\", \"target\": \"expiration\", \"file_field\": \"N\"}}', NULL, NULL, NULL, '2026-09-18 01:39:34', '2026-09-26 01:18:03', '2026-10-05'),
(28, 1001, 'drocerca_bot', 'http://drocerca.proteoerp.org:8082/proteoerp/portalcli', NULL, 'W008B3', 'eyJpdiI6Imd5bTI0dGhyLzJ3dDVjUVhnQjMwR1E9PSIsInZhbHVlIjoiSkg2Zi9UYUNNU0o5amo5ejlFY1Y1dz09IiwibWFjIjoiODM0NWZkYTc2MTFiZThiZmZiZTA2M2RmMzFiOTc4YzIyNWRmZTEyMTkxYjhlYmJlNTYyYzBhMDBkM2Y2YzMyNCIsInRhZyI6IiJ9', NULL, 1, 1, NULL, NULL, '[]', NULL, NULL, NULL, '2026-09-30 16:24:05', '2026-09-30 16:27:23', '2026-10-05'),
(29, 1005, 'dromega_bot', 'https://www.drogueriamega.com/mydas/', NULL, 'Farmacia_Barrio_Sucre', 'eyJpdiI6IjJmdDJWbnYvUmJZS3MvVXRYdGdVSWc9PSIsInZhbHVlIjoiVytGOC9ZNzZqY1drZXQ5UXl5WGVvQT09IiwibWFjIjoiNmU3ODU5NDY5MmFiMjllMWJlZjE5NWQ3MjY1ZDY2M2YxYWQ3MDZlZjA2NzAyOWQ0OTBjN2Q4MjE2NzU3M2U5NCIsInRhZyI6IiJ9', NULL, 1, 1, NULL, '{\"lines\": {\"0\": {\"type\": \"string\", \"field\": \"tipo\"}, \"1\": {\"type\": \"integer\", \"field\": \"fact_num\"}, \"2\": {\"type\": \"string\", \"field\": \"numcon\"}, \"3\": {\"type\": \"string\", \"field\": \"codigo_producto\"}, \"4\": {\"type\": \"string\", \"field\": \"barcode\"}, \"5\": {\"type\": \"string\", \"field\": \"descripcion_producto\"}, \"6\": {\"type\": \"integer\", \"field\": \"quantity\"}, \"8\": {\"type\": \"decimal\", \"field\": \"total_amount\"}, \"10\": {\"type\": \"decimal\", \"field\": \"unit_cost\"}, \"11\": {\"type\": \"string\", \"field\": \"lot_number\"}, \"12\": {\"type\": \"date\", \"field\": \"expiration_date\", \"format\": \"d/m/Y\"}, \"13\": {\"type\": \"decimal\", \"field\": \"porcentaje_iva\"}}, \"header\": {\"0\": {\"type\": \"string\", \"field\": \"tipo\"}, \"1\": {\"type\": \"integer\", \"field\": \"invoice_number\"}, \"2\": {\"type\": \"string\", \"field\": \"control_number\"}, \"3\": {\"type\": \"date\", \"field\": \"created_invoice_date\", \"format\": \"d/m/Y\"}, \"8\": {\"type\": \"decimal\", \"field\": \"total_amount\"}, \"13\": {\"type\": \"decimal\", \"field\": \"tax_amount\"}}, \"decimals\": 2, \"separator\": \";\", \"decimal_separator\": \".\"}', '[{\"type\": \"string\", \"target\": \"cod_supplier\", \"file_field\": \"codigo_producto\"}, {\"type\": \"string\", \"target\": \"barcode_match\", \"file_field\": \"codigo_barras\"}, {\"type\": \"string\", \"target\": \"name\", \"file_field\": \"descripcion_producto\"}, {\"type\": \"date\", \"target\": \"expiration\", \"file_field\": \"fecha_lote\"}, {\"type\": \"decimal\", \"file_field\": \"precio_unitario\"}, {\"type\": \"decimal\", \"file_field\": \"porcentaje_oferta_vigente\"}, {\"type\": \"decimal\", \"target\": \"unit_cost\", \"file_field\": \"precio_unitario_final\"}, {\"type\": \"integer\", \"target\": \"quantity\", \"file_field\": \"stock_disponible\"}]', NULL, NULL, NULL, '2026-10-01 16:56:02', '2026-10-01 16:56:02', '2026-10-05');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `supplier_connections`
--
ALTER TABLE `supplier_connections`
  ADD PRIMARY KEY (`id`),
  ADD KEY `supplier_connections_supplier_id_foreign` (`supplier_id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `supplier_connections`
--
ALTER TABLE `supplier_connections`
  MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `supplier_connections`
--
ALTER TABLE `supplier_connections`
  ADD CONSTRAINT `supplier_connections_supplier_id_foreign` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
